.pragma library
// Henri UI user preferences — the global switches Motion.js reads.
// Prefs.js is generated by System Settings (omarchy-settings, Accessibility ›
// Display) and is machine state: never edit it by hand and never commit it.
// This file holds the defaults; wherever Prefs.js is missing it is created
// from here (the Settings backend, henri-ui-sync for vendored copies).
var reduceMotion = false
var reduceTransparency = false
// Control Center › Experiments › No effects (henri-render-power): the
// compositor blur is off, so glass would only look washed out.
var noEffects = false
